### PR TITLE
CBBI-139: Switch HealthAPT envs to deploy BB API webapp in Wildfly: dev

### PR DESCRIPTION
**Pull request by karlmdavis**
This PR contains the code changes required for http://issues.hhsdevcloud.us/browse/CBBI-139.

### CODE REVIEW

**Comment by karlmdavis** [comment]
@dho937 or @sbrockhoff: Could you please review this today or tomorrow? I need to hand it off to the IT folks so that they can go deploy things in test and prod.

**Comment by karlmdavis** [comment]
Actually... today would be best, if at all possible. I'm out tomorrow, and I suspect folks would like to see this deployed everywhere by tomorrow.

**Comment by dho937** [comment]
:+1:

**Comment by karlmdavis** [comment]
Thanks!

**Comment by sbrockhoff** [comment]
:+1:

**Pull request merged**
